# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno Tests

on:
    push:
        branches: ["v0.0.2"]
    pull_request:
        branches: ["v0.0.2"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v4
              with:
                  ref: v0.0.2

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.2.11

            - name: Run tests
              run: deno test
